---
trainer:
  class_path: eva.Trainer
  init_args:
    default_root_dir: &LIGHTNING_ROOT ${oc.env:LIGHTNING_ROOT, logs/dino_vits16/offline/patch_camelyon}
    max_epochs: &MAX_EPOCHS 20
    callbacks:
      - class_path: eva.callbacks.EmbeddingsWriter
        init_args:
          output_dir: &EMBEDDINGS_DIR ${oc.env:EMBEDDINGS_ROOT, ./data/embeddings}/patch_camelyon
          dataloader_idx_map:
            0: train
            1: val
            2: test
          backbone:
            class_path: eva.models.ModelFromFunction
            init_args:
              path: torch.hub.load
              arguments:
                repo_or_dir: facebookresearch/dino:main
                model: dino_vits16
                pretrained: true
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: epoch
      - class_path: eva.loggers.TensorBoardLogger
        init_args:
          filename: best
          save_last: true
          save_top_k: 1
          monitor: &MONITOR_METRIC val/BinaryAccuracy
          mode: &MONITOR_METRIC_MODE max
    logger:
      - class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
          save_dir: *LIGHTNING_ROOT
          name: ""
model:
  class_path: eva.HeadModule
  init_args:
    head:
      class_path: torch.nn.Linear
      init_args:
        in_features: 384
        out_features: 1
    criterion: torch.nn.BCEWithLogitsLoss
    optimizer:
      class_path: torch.optim.SGD
      init_args:
        lr: 0.0125
        momentum: 0.9
        weight_decay: 0.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CosineAnnealingLR
      init_args:
        T_max: *MAX_EPOCHS
        eta_min: 0.0001
    metrics:
      common:
        - class_path: eva.metrics.AverageLoss
        - class_path: eva.metrics.BinaryClassificationMetrics
data:
  class_path: eva.DataModule
  init_args:
    datasets:
      train:
        class_path: eva.vision.data.datasets.embeddings.PatchEmbeddingDataset
        init_args: &DATASET_ARGS
          root: *EMBEDDINGS_DIR
          split: train
          column_mapping:
            path: embedding
          target_transforms:
            class_path: eva.vision.data.transforms.common.ArrayToFloatTensor
      val:
        class_path: eva.vision.data.datasets.embeddings.PatchEmbeddingDataset
        init_args:
          <<: *DATASET_ARGS
          split: val
      test:
        class_path: eva.vision.data.datasets.embeddings.PatchEmbeddingDataset
        init_args:
          <<: *DATASET_ARGS
          split: test
      predict:
        - class_path: eva.vision.datasets.PatchCamelyon
          init_args: &PREDICT_DATASET_ARGS
            root: ${oc.env:DATA_ROOT, ./data}/patch_camelyon
            split: train
            download: ${oc.env:DOWNLOAD_DATA, true}
            image_transforms:
              class_path: eva.vision.data.transforms.common.ResizeAndCrop
              init_args:
                size: ${oc.env:RESIZE_DIM, 224}  
                mean: ${oc.env:NORMALIZE_MEAN, [0.485, 0.456, 0.406]} 
                std: ${oc.env:NORMALIZE_STD, [0.229, 0.224, 0.225]}
        - class_path: eva.vision.datasets.PatchCamelyon
          init_args:
            <<: *PREDICT_DATASET_ARGS
            split: val
        - class_path: eva.vision.datasets.PatchCamelyon
          init_args:
            <<: *PREDICT_DATASET_ARGS
            split: test
    dataloaders:
      train:
        batch_size: &TRAIN_BATCH_SIZE ${oc.env:TRAIN_BATCH_SIZE, 256}
        shuffle: true
      val:
        batch_size: &EVAL_BATCH_SIZE ${oc.env:EVAL_BATCH_SIZE, 128}
      test:
        batch_size: *EVAL_BATCH_SIZE
      predict:
        batch_size: *EVAL_BATCH_SIZE
