site_name: eva
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.indexes
    - search.suggest
    - search.highlight
plugins:
  search: null
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: table
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          members_order: source
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_signature: false
          show_root_heading: true
          filters:
          - '!^_'
markdown_extensions:
  toc:
    toc_depth: 2
nav:
  - eva: index.md
  - User Guide:
      - user-guide/index.md
      - Getting started: user-guide/getting_started.md
      - How to use eva: user-guide/how_to_use.md
      - Tutorials:
        - user-guide/tutorials/index.md
        - user-guide/tutorials/eva_subcommands.md
        - user-guide/tutorials/replicate_results.md
        - user-guide/tutorials/evaluate_resnet.md
      - Replicate evaluations: user-guide/replicate_evaluations.md
  - Reference API:
    - reference/index.md
    - Interface: reference/interface.md
    - Callbacks: reference/callbacks.md
    - Data:
      - reference/data/dataloaders.md
      - reference/data/datamodules.md
      - reference/data/datasets.md
    - Metrics: 
      - reference/metrics/index.md
      - reference/metrics/core.md
      - reference/metrics/defaults.md
      - reference/metrics/average_loss.md
      - reference/metrics/binary_balanced_accuracy.md
    - Models: 
      - Modules: reference/models/modules.md
      - Networks: reference/models/networks.md
    - Trainers:
      - Trainer: reference/trainers/trainer.md
      - Functional: reference/trainers/functional.md
    - Utils:
      - Multiprocessing: reference/utils/multiprocessing.md
      - Workers: reference/utils/workers.md
    - Vision:
      - reference/vision/index.md
      - Data:
        - reference/vision/data/index.md
        - reference/vision/data/datasets.md
        - reference/vision/data/transforms.md
      - Models:
        - reference/vision/models/networks.md
      - Utils:
        - IO: reference/vision/utils/io.md
  - Datasets: 
    - datasets/index.md
    - BACH: datasets/bach.md
    - CRC: datasets/crc.md
    - MHIST: datasets/mhist.md
    - PatchCamelyon: datasets/patch_camelyon.md
    - TotalSegmentator: datasets/total_segmentator.md
