site_name: eva

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.indexes

plugins:
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: table
          filters:
          - '!^(?!__init__)_'
          
nav:
  - eva: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Reference API:
    - reference/index.md
    - Interface: reference/interface.md
    - Data:
      - reference/data/dataloaders.md
      - reference/data/datamodules.md
      - reference/data/datasets.md
    - Metrics: reference/metrics.md
    - Models: 
      - Modules: reference/models/modules.md
    - Trainers: reference/trainers.md
    - Vision:
      - reference/vision/index.md
      - reference/vision/data.md
      - reference/vision/file_io.md
      - reference/vision/models.md
  - Datasets: 
    - datasets/index.md
    - PatchCamelyon: datasets/patch_camelyon.md
    - BACH: datasets/bach.md
    - TotalSegmentator: datasets/total_segmentator.md
