site_name: eva
repo_name: kaiko-eva
repo_url: https://github.com/kaiko-ai/eva
theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
  favicon: images/eva-stripes.png
  logo: images/eva-stripes.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
plugins:
  search: null
  mike: null
  mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: table
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          members_order: source
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_signature: false
          show_root_heading: true
          filters:
          - '!^_'
extra:
  version:
    provider: mike
    default:
      - latest
      - dev
markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction: index.md
  - Leaderboards: leaderboards.md
  - User Guide:
      - user-guide/index.md
      - Getting started:
        - user-guide/getting-started/installation.md
        - user-guide/getting-started/how_to_use.md
      - Tutorials:
        - user-guide/tutorials/offline_vs_online.md
        - user-guide/tutorials/evaluate_resnet.md
      - Advanced user guide:
        - user-guide/advanced/replicate_evaluations.md
        - user-guide/advanced/model_wrappers.md
  - Datasets: 
    - datasets/index.md
    - WSI:
      - Patch-level:
        - BACH: datasets/bach.md
        - CRC: datasets/crc.md
        - MHIST: datasets/mhist.md
        - PatchCamelyon: datasets/patch_camelyon.md
      - Slide-level:
        - Camelyon16: datasets/camelyon16.md
        - PANDA: datasets/panda.md
    - Radiology:
      - TotalSegmentator: datasets/total_segmentator.md
  - Reference API:
    - reference/index.md
    - Core:
      - Interface: reference/core/interface.md
      - Callbacks: reference/core/callbacks.md
      - Data:
        - reference/core/data/dataloaders.md
        - reference/core/data/datamodules.md
        - reference/core/data/datasets.md
        - reference/core/data/transforms.md
      - Metrics: 
        - reference/core/metrics/index.md
        - reference/core/metrics/core.md
        - reference/core/metrics/defaults.md
        - reference/core/metrics/average_loss.md
        - reference/core/metrics/binary_balanced_accuracy.md
      - Models: 
        - Modules: reference/core/models/modules.md
        - Networks: reference/core/models/networks.md
      - Trainers:
        - Trainer: reference/core/trainers/trainer.md
        - Functional: reference/core/trainers/functional.md
      - Loggers: reference/core/loggers/loggers.md
      - Utils:
        - Multiprocessing: reference/core/utils/multiprocessing.md
        - Workers: reference/core/utils/workers.md
    - Vision:
      - reference/vision/index.md
      - Data:
        - reference/vision/data/index.md
        - reference/vision/data/datasets.md
        - reference/vision/data/transforms.md
      - Models:
        - reference/vision/models/networks.md
      - Utils:
        - IO: reference/vision/utils/io.md
