---
trainer:
  class_path: eva.Trainer
  init_args:
    default_root_dir: &OUTPUT_DIR ${oc.env:OUTPUT_DIR, logs/dino_vits16/patch_camelyon}
    max_epochs: &MAX_EPOCHS 20
    callbacks:
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: epoch
    logger:
      - class_path: pytorch_lightning.loggers.CSVLogger
        init_args:
          save_dir: *OUTPUT_DIR
          name: ""
          version: ""
      - class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
          save_dir: *OUTPUT_DIR
          name: ""
          version: ""
model:
  class_path: eva.HeadModule
  init_args:
    backbone:
      class_path: eva.models.ModelFromFunction
      init_args:
        path: torch.hub.load
        arguments:
          repo_or_dir: facebookresearch/dino:main
          model: dino_vits16
          pretrained: true
    head:
      class_path: torch.nn.Linear
      init_args:
        in_features: 27648
        out_features: &NUM_CLASSES 2
    criterion: torch.nn.CrossEntropyLoss
    optimizer:
      class_path: torch.optim.SGD
      init_args:
        lr: 0.1
        momentum: 0.9
        weight_decay: 0.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CosineAnnealingLR
      init_args:
        T_max: *MAX_EPOCHS
        eta_min: 0.01
    metrics:
      common:
        - class_path: eva.metrics.AverageLoss
        - class_path: eva.metrics.MulticlassClassificationMetrics
          init_args:
            num_classes: *NUM_CLASSES
data:
  class_path: eva.DataModule
  init_args:
    datasets:
      train:
        class_path: eva.vision.datasets.PatchCamelyon
        init_args:
          root: ${oc.env:DATA_ROOT, ./data}/patch_camelyon
          split: train
          download: true
          image_transforms:
            class_path: torchvision.transforms.v2.Compose
            init_args:
              transforms:
                - class_path: torchvision.transforms.v2.ToImage
                - class_path: torchvision.transforms.v2.Resize
                  init_args:
                    size: 224
                - class_path: torchvision.transforms.v2.ConvertImageDtype
                - class_path: torchvision.transforms.v2.Normalize
                  init_args:
                    mean: &NORMALIZE_MEAN [0.485, 0.456, 0.406]
                    std: &NORMALIZE_STD [0.229, 0.224, 0.225]
      val:
        class_path: eva.vision.datasets.PatchCamelyon
        init_args:
          root: ${oc.env:DATA_ROOT, ./data}/patch_camelyon
          split: valid
          download: true
          image_transforms:
            class_path: torchvision.transforms.v2.Compose
            init_args:
              transforms:
                - class_path: torchvision.transforms.v2.ToImage
                - class_path: torchvision.transforms.v2.Resize
                  init_args:
                    size: 224
                - class_path: torchvision.transforms.v2.ConvertImageDtype
                - class_path: torchvision.transforms.v2.Normalize
                  init_args:
                    mean: *NORMALIZE_MEAN
                    std: *NORMALIZE_STD
    dataloaders:
      train:
        batch_size: &BATCH_SIZE 256
        shuffle: true
      val:
        batch_size: *BATCH_SIZE
