trainer:
  class_path: eva.Trainer
  init_args:
    n_runs: &N_RUNS ${oc.env:N_RUNS, 2}
    default_root_dir: &OUTPUT_DIR ${oc.env:OUTPUT_DIR, ./logs/patch_camelyon_mcqa}
    accelerator: auto
    precision: bf16
    checkpoint_type: null
    callbacks:
      - class_path: eva.callbacks.ConfigurationLogger
model:
  class_path: eva.multimodal.models.modules.VisionLanguageModule
  init_args:
    model:
      class_path: eva.multimodal.models.wrappers.ModelFromRegistry
      init_args:
        model_name: ${oc.env:MODEL_NAME, anthropic/claude-3-5-sonnet-20240620}
        model_extra_kwargs: ${oc.env:MODEL_EXTRA_KWARGS, null}
    metrics:
      evaluation:
        patch_camelyon_mcqa_accuracy:
          class_path: eva.multimodal.metrics.vqa_metrics.TextBinaryAccuracy
          init_args:
            options:
              - "A"
              - "B"
data:
  class_path: eva.DataModule
  init_args:
    datasets:
      test:
        - class_path: eva.multimodal.data.datasets.PatchCamelyon
          init_args:
            root: ${oc.env:DATA_ROOT, /mnt/localdisk/data/patch_camelyon}
            split: test
            download: ${oc.env:DOWNLOAD_DATA, false}
            transforms:
              image:
                class_path: torchvision.transforms.v2.Resize
                init_args:
                  size: ${oc.env:RESIZE_DIM, 96}
    dataloaders:
      test:
        batch_size: ${oc.env:BATCH_SIZE, 8}
        shuffle: true
        num_workers: 0
        pin_memory: false
        persistent_workers: false
        prefetch_factor: null
        drop_last: true