---
trainer:
  class_path: eva.Trainer
  init_args:
    default_root_dir: &OUTPUT_ROOT ${oc.env:OUTPUT_ROOT, logs/${oc.env:DINO_BACKBONE, dino_vits16}/online/patch_camelyon}
    max_steps: &MAX_STEPS 12500
    callbacks:
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
        init_args:
          logging_interval: epoch
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
          filename: best
          save_last: true
          save_top_k: 1
          monitor: &MONITOR_METRIC ${oc.env:MONITOR_METRIC, val/BinaryAccuracy}
          mode: &MONITOR_METRIC_MODE ${oc.env:MONITOR_METRIC_MODE, max}
      - class_path: pytorch_lightning.callbacks.EarlyStopping
        init_args:
          min_delta: 0
          patience: 17
          monitor: *MONITOR_METRIC
          mode: *MONITOR_METRIC_MODE
    logger:
      - class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
          save_dir: *OUTPUT_ROOT
          name: ""
model:
  class_path: eva.HeadModule
  init_args:
    backbone:
      class_path: eva.models.ModelFromFunction
      init_args:
        path: torch.hub.load
        arguments:
          repo_or_dir: facebookresearch/dino:main
          model: ${oc.env:DINO_BACKBONE, dino_vits16}
          pretrained: ${oc.env:PRETRAINED, true}
        checkpoint_path: ${oc.env:CHECKPOINT_PATH, null}
    head:
      class_path: torch.nn.Linear
      init_args:
        in_features: ${oc.env:IN_FEATURES, 384}
        out_features: 1
    criterion: torch.nn.BCEWithLogitsLoss
    optimizer:
      class_path: torch.optim.SGD
      init_args:
        lr: &LR_VALUE 0.00064
        momentum: 0.9
        weight_decay: 0.0
    lr_scheduler:
      class_path: torch.optim.lr_scheduler.CosineAnnealingLR
      init_args:
        T_max: *MAX_STEPS
        eta_min: 0.0
    metrics:
      common:
        - class_path: eva.metrics.AverageLoss
        - class_path: eva.metrics.BinaryClassificationMetrics
data:
  class_path: eva.DataModule
  init_args:
    datasets:
      train:
        class_path: eva.vision.datasets.PatchCamelyon
        init_args: &DATASET_ARGS
          root: ${oc.env:DATA_ROOT, ./data}/patch_camelyon
          split: train
          download: ${oc.env:DOWNLOAD_DATA, true}
          image_transforms:
            class_path: eva.vision.data.transforms.common.ResizeAndCrop
            init_args:
              size: ${oc.env:RESIZE_DIM, 224}  
              mean: ${oc.env:NORMALIZE_MEAN, [0.485, 0.456, 0.406]} 
              std: ${oc.env:NORMALIZE_STD, [0.229, 0.224, 0.225]}
          target_transforms:
            class_path: eva.vision.data.transforms.common.ArrayToFloatTensor
      val:
        class_path: eva.vision.datasets.PatchCamelyon
        init_args:
          <<: *DATASET_ARGS
          split: val
      test:
        class_path: eva.vision.datasets.PatchCamelyon
        init_args:
          <<: *DATASET_ARGS
          split: test
    dataloaders:
      train:
        batch_size: &BATCH_SIZE ${oc.env:BATCH_SIZE, 64}
        shuffle: true
      val:
        batch_size: *BATCH_SIZE
      test:
        batch_size: *BATCH_SIZE
