---
model:
  class_path: eva.HeadModule
  init_args:
    backbone:
      class_path: eva.models.ModelFromFunction
      init_args:
        path: torch.hub.load
        arguments:
          repo_or_dir: facebookresearch/dino:main
          model: dino_vits16
          pretrained: true
    head:
      class_path: torch.nn.Linear
      init_args:
        in_features: 384
