---
trainer:
  class_path: eva.Trainer
  init_args:
    checkpoint_type: null
model:
  class_path: eva.language.models.TextModule
  init_args:
    prompt: "Instruction: You are an expert in biomedical research. Please carefully read the question and the relevant context and answer with yes, no, or maybe. Only answer with one of these three words."
    model:
      class_path: eva.language.models.LiteLLMTextModel
      init_args:
        model_name_or_path: ${oc.env:MODEL_NAME, anthropic/claude-sonnet-4-0}
        # model_kwargs:
          # temperature: 0.01 # should be strictly positive for HF models
          # max_new_tokens: 1 # used for HF
    metrics:
      common:
        - class_path: eva.metrics.MulticlassClassificationMetrics
          init_args:
            num_classes: 3
            input_type: "discrete"
    postprocess:
      predictions_transforms:
        - class_path: eva.language.utils.str_to_int_tensor.CastStrToIntTensor
data:
  class_path: eva.DataModule
  init_args:
    datasets:
      val:
        class_path: eva.language.datasets.PubMedQA
        init_args: &DATASET_ARGS
          root: ${oc.env:DATA_ROOT, ./data/pubmedqa}
          split: null
          download: true
    dataloaders:
      val:
        batch_size: &BATCH_SIZE ${oc.env:BATCH_SIZE, 16}
        num_workers: &N_DATA_WORKERS ${oc.env:N_DATA_WORKERS, 1}
        shuffle: false
        collate_fn: eva.core.data.dataloaders.text_collate_fn