---
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setting up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: "3.10"
        architecture: x64
    - name: Setting up NOX
      uses: wntrblm/nox@2024.03.02
      with:
        python-versions: "3.10"
    - name: Performing lint checks
      run: nox -s lint
    - name: Performing static type checks
      run: nox -s check

  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - "3.10"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Setting up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Setting up nox
      uses: wntrblm/nox@2024.03.02
      with:
        python-versions: ${{ matrix.python-version }}
    - name: Executing unit tests
      run: nox -s test
