---
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.13"]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Setting up PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setting up NOX
      uses: wntrblm/nox@2022.11.21
      with:
        python-versions: ${{ matrix.python-version }}
    - name: "Linting tests"
      run: nox -s lint
    - name: "Typing checks"
      run: nox -s check
    - name: "Unit Tests"
      run: nox -s test
