---
name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setting up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Setting up NOX
      uses: wntrblm/nox@2023.04.22
      with:
        python-versions: ${{ matrix.python-version }}
    - name: Linting tests
      run: nox -s lint
    - name: Type annotations checks
      run: nox -s check

  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - "3.10"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setting up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Setting up NOX
      uses: wntrblm/nox@2023.04.22
      with:
        python-versions: ${{ matrix.python-version }}
    - name: Unit Tests
      run: nox -s test
