---
name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setting up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setting up nox
        uses: wntrblm/nox@5656fcedc31a1ea37d016e4d94d00185330cc528 # 2024.04.15
        with:
          python-versions: "3.10"
      - name: Configure Git Credentials
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
      - name: Deploy Documentation
        run: |
          git fetch origin gh-pages:gh-pages
          nox -s docs -- deploy --update-aliases dev
          git push origin gh-pages
