name: Build/Publish Develop Docs 
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setting up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setting up nox
        uses: wntrblm/nox@2024.03.02
        with:
          python-versions: "3.10"
      - name: Build Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch origin gh-pages:gh-pages
          nox -s docs -- --update-aliases dev
          git push origin gh-pages
