---
name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Setting up PDM
        uses: pdm-project/setup-pdm@568ddd69406b30de1774ec0044b73ae06e716aa4 # v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setting up nox
        uses: wntrblm/nox@4c8e89164d90718312e4819a48243797924f55a9 # 2024.03.02
        with:
          python-versions: "3.10"
      - name: Configure Git Credentials
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
      - name: Deploy Documentation
        run: |
          git fetch origin gh-pages:gh-pages
          nox -s docs -- deploy --update-aliases dev
          git push origin gh-pages
